export const SET_CURRENT_GAME = "SET_CURRENT_GAME";
export const SET_GAME_CONTENT_TYPE = "SET_GAME_CONTENT_TYPE";

export const ADD_RULE_TO_RULESET = "ADD_RULE_TO_RULESET";
export const SET_CURRENT_RULE = "SET_CURRENT_RULE";
export const SET_CURRENT_RULESET = "SET_CURRENT_RULESET";

export const SET_CURRENT_MODAL = "SET_CURRENT_MODAL";

export const UPDATE_PATH = "@@router/UPDATE_PATH";


export const SET_CURRENT_USER = "SET_CURRENT_USER";
