export const SET_CURRENT_GAME = "SET_CURRENT_GAME";

export const ADD_RULE_TO_RULESET = "ADD_RULE_TO_RULESET";
export const SET_CURRENT_RULE = "SET_CURRENT_RULE";

export const SET_CURRENT_MODAL = "SET_CURRENT_MODAL";
