export const SET_CURRENT_GAME = "SET_CURRENT_GAME";

export const ADD_RULE_TO_RULESET = "ADD_RULE_TO_RULESET";
export const INCREASE_RULE_COUNT = "INCREASE_RULE_COUNT";

export const SET_CURRENT_MODAL = "SET_CURRENT_MODAL";
